from pathlib import Path
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn

OUT=Path("docs")
def font(run,size=11,bold=False,color=None):
 run.font.name="Calibri";run._element.rPr.rFonts.set(qn("w:ascii"),"Calibri");run._element.rPr.rFonts.set(qn("w:hAnsi"),"Calibri");run.font.size=Pt(size);run.bold=bold
 if color: run.font.color.rgb=RGBColor(*color)
def make(title,subtitle,sections,path):
 d=Document();s=d.sections[0];s.top_margin=s.bottom_margin=s.left_margin=s.right_margin=Inches(1)
 normal=d.styles["Normal"];normal.font.name="Calibri";normal.font.size=Pt(11);normal.paragraph_format.space_after=Pt(6);normal.paragraph_format.line_spacing=1.25
 for style,size in [("Heading 1",16),("Heading 2",13),("Heading 3",12)]:
  st=d.styles[style];st.font.name="Calibri";st.font.size=Pt(size);st.font.color.rgb=RGBColor(46,116,181)
 p=d.add_paragraph();p.paragraph_format.space_after=Pt(4);font(p.add_run(title),25,True,(11,37,69))
 p=d.add_paragraph();font(p.add_run(subtitle),12,False,(80,80,80));p.paragraph_format.space_after=Pt(20)
 for heading,body in sections:
  d.add_heading(heading,level=1)
  for kind,text in body:
   if kind=="p": d.add_paragraph(text)
   elif kind=="b": d.add_paragraph(text,style="List Bullet")
   elif kind=="h": d.add_heading(text,level=2)
 footer=s.footer.paragraphs[0];footer.alignment=WD_ALIGN_PARAGRAPH.RIGHT;font(footer.add_run("VectorVault | 2026"),9,False,(100,100,100))
 d.core_properties.title=title;d.core_properties.author="VectorVault"
 d.save(path)

guide=[
("Product overview",[("p","VectorVault is a modular, multi-tenant semantic knowledge platform. Applications upload documents, retrieve relevant chunks with metadata filters, and ask grounded questions with citations."),("p","The core design goal is explainable production engineering: PostgreSQL owns relational truth, Pinecone owns production vectors, and the API keeps both behind clear boundaries.")]),
("Architecture and technology choices",[("p","FastAPI exposes versioned REST endpoints. SQLAlchemy models users, workspaces, collections, documents, chunks, and API keys. Redis is reserved for distributed rate limits and cache entries. Next.js provides a minimal operator UI."),("b","Pinecone: managed vector search and metadata filters; local VectorStore for development/testing."),("b","PostgreSQL: constraints, transactions, relational metadata, and tenant-scoped query patterns."),("b","FastAPI: typed validation, async-friendly web layer, and automatic OpenAPI documentation.")]),
("Ingestion and retrieval",[("p","An upload is checked for allowed type and size, checksummed for duplicate detection, text-extracted, normalized, chunked, embedded, upserted, and recorded. Only a fully successful flow becomes COMPLETED; failures are marked FAILED."),("p","The default chunk target is 900 characters with 150-character overlap. Smaller chunks can improve retrieval precision but increase embedding cost; larger chunks preserve context but can dilute ranking."),("p","Search embeds a query and applies workspace plus collection metadata filters at the vector layer. Similarity scores rank results; they are not probabilities.")]),
("RAG and safety",[("p","RAG retrieves context before answer generation. The prompt must keep system policy, user question, and untrusted retrieved documents distinct. Answers should cite source chunks, state uncertainty, and never execute instructions found in a document."),("p","Prompt injection is a residual risk. Limit tools, isolate tenants, evaluate adversarial documents, and avoid treating retrieved text as control instructions.")]),
("Authentication and tenancy",[("p","Passwords use Argon2 hashing. Access and refresh tokens have distinct types and expirations. Every resource lookup verifies workspace membership server-side; only owners manage API keys and collection deletion."),("p","API keys use cryptographic randomness. A raw value appears once; only its SHA-256 digest, prefix, timestamps, and revocation state are persisted.")]),
("Operations, testing, and scale",[("p","Docker Compose starts the API, PostgreSQL, and Redis. Health and readiness endpoints support orchestration. CI runs Ruff, tests, and a Docker build."),("p","The MVP ingests synchronously. For scale, introduce durable jobs, retry/idempotency controls, object storage, Redis rate limits, metrics, and horizontal API replicas. Pinecone or LLM outages should surface controlled errors and retryable jobs.")]),
("Alternatives and trade-offs",[("p","Pinecone minimizes vector-operations burden and is appropriate for a hosted production service. ChromaDB is lightweight for local development. pgvector consolidates storage with PostgreSQL and can be ideal for moderate scale or SQL-centric filtering, but makes vector capacity and operations a database concern."),("p","No architecture choice is universal: hosted vector infrastructure trades cost/control for operational simplicity; a local/pgvector choice trades convenience for tighter ownership.")]),]
make("VectorVault Project Guide","A practical guide to the secure semantic retrieval platform",guide,OUT/"VectorVault_Project_Guide.docx")
questions=[
("Explain your project.",[("h","Short interview answer"),("p","VectorVault is a multi-tenant knowledge-retrieval API. It turns uploaded documents into embeddings, stores production vectors in Pinecone, and returns filtered search results or grounded RAG answers with source references."),("h","Deep technical explanation"),("p","PostgreSQL owns identities and document metadata; a VectorStore interface decouples services from Pinecone. Each request is authorized against a workspace before a vector query includes the workspace namespace/filter."),("h","Likely follow-up"),("p","How do you prevent cross-tenant results?"),("h","Strong follow-up answer"),("p","Authorization happens on the server before search. The query includes workspace metadata and namespace, and chunks are verified through workspace-owned relational records." )]),
("Why Pinecone instead of ChromaDB or pgvector?",[("h","Short interview answer"),("p","Pinecone is the production choice for managed vector search and metadata filtering. ChromaDB is useful locally, and pgvector is compelling when operational consolidation and SQL joins matter more than a dedicated vector service."),("h","Deep technical explanation"),("p","The app depends on VectorStore rather than vendor calls, so the choice is reversible. Pinecone reduces index-serving work; pgvector reduces systems count but can shift vector scaling pressure into PostgreSQL."),("h","Likely follow-up"),("p","What would make you choose pgvector?"),("h","Strong follow-up answer"),("p","A moderate corpus requiring transactional SQL joins and a team already expert at operating Postgres could reasonably prioritize pgvector." )]),
("How does ingestion handle failure?",[("h","Short interview answer"),("p","The document stays PROCESSING until extraction, chunking, embedding, vector upsert, and metadata persistence complete. A failure becomes FAILED rather than partially COMPLETE."),("h","Deep technical explanation"),("p","A production evolution uses a durable job with idempotency keys, batch checkpoints, compensating vector deletes, retries with backoff, and a dead-letter workflow."),("h","Likely follow-up"),("p","What happens if Pinecone fails after embeddings?"),("h","Strong follow-up answer"),("p","Persist job state, retry the idempotent vector batch, and do not make the document searchable until its expected chunk count is confirmed." )]),
("How do you secure API keys and passwords?",[("h","Short interview answer"),("p","Passwords use Argon2. API keys are randomly generated, displayed once, and only SHA-256 digests are stored. Both are excluded from logs."),("h","Deep technical explanation"),("p","Key operations require owner membership. A production request middleware hashes supplied keys, finds only active records, updates last-used time carefully, and supports rotation/revocation."),("h","Likely follow-up"),("p","How would you handle a leaked key?"),("h","Strong follow-up answer"),("p","Revoke it immediately, issue a replacement, audit its use, limit blast radius by workspace scope, and alert on anomalous patterns." )]),
("How would you scale to millions of documents?",[("h","Short interview answer"),("p","Separate ingestion into queued workers, store originals in object storage, batch embeddings and vector upserts, horizontally scale stateless APIs, and observe queue depth, latency, failures, and tenant limits."),("h","Deep technical explanation"),("p","Keep PostgreSQL for metadata and Pinecone for ANN retrieval. Add backpressure, idempotency, usage quotas, and staged reindexing for embedding-model changes."),("h","Likely follow-up"),("p","How do you prevent embedding drift?"),("h","Strong follow-up answer"),("p","Version the model on every chunk, dual-write/reindex into a new namespace, evaluate retrieval on labeled queries, then switch traffic after acceptance." )]),
("Key concepts",[("p","Embeddings map semantic meaning to vectors; cosine similarity measures direction; top-K returns the nearest candidates. ANN indexes trade exactness for latency. Recall@K asks whether relevant documents appear in the top K; Precision@K asks how much of the returned set is relevant. RAG differs from fine-tuning because it supplies current retrieved context at query time rather than changing model weights.")]),
("Resume bullets",[("b","Built VectorVault, a FastAPI semantic-search platform with tenant-scoped document ingestion, VectorStore abstraction, and grounded retrieval APIs."),("b","Implemented Argon2 authentication, workspace RBAC, one-time API-key display with hashed persistence, and secure file validation."),("b","Containerized PostgreSQL/Redis-backed local environment and added CI, tests, design documentation, and evaluation fixtures."),("p","ATS-focused: FastAPI, Python, PostgreSQL, Pinecone, RAG, vector search, JWT, RBAC, Docker, CI/CD, semantic retrieval.")])]
make("VectorVault Interview Concepts","Technical interview preparation and explainable design decisions",questions,OUT/"VectorVault_Interview_Concepts.docx")
